# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/projects/vivado_project/mips_components/mips_components.srcs/sources_1/ip/imem/imem.xci
# IP: The module: 'imem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/projects/vivado_project/mips_components/mips_components.srcs/sources_1/ip/imem/imem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/projects/vivado_project/mips_components/mips_components.srcs/sources_1/ip/imem/imem.xci
# IP: The module: 'imem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/projects/vivado_project/mips_components/mips_components.srcs/sources_1/ip/imem/imem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
